// 时间格式化
const DATE_TIME_FORMAT_STRING = 'YYYY-MM-DD HH:mm:ss';
const DATE_FORMAT_STRING = 'YYYY-MM-DD';
const TIME_FORMAT_STRING = 'HH:mm:ss';
const HOUR_MIN_FORMAT_STRING = 'HH:mm';
const SLASH_DATE_TIME_FORMAT_STRING = 'YYYY/MM/DD HH:mm:ss';

// 数字格式化
const MONEY_FORMAT = '0,0.00';
const INTEGER_FORMAT = '0,0';
const PERCENTAGE_FORMAT = '0.00%';

export {
  DATE_TIME_FORMAT_STRING,
  DATE_FORMAT_STRING,
  TIME_FORMAT_STRING,
  HOUR_MIN_FORMAT_STRING,
  SLASH_DATE_TIME_FORMAT_STRING,

  MONEY_FORMAT,
  INTEGER_FORMAT,
  PERCENTAGE_FORMAT
};
